## File generated by the BNF Converter (bnfc 2.9.3).
JAVAC=javac
JAVA_CUP_PATH=third_party/java-cup-11b-runtime.jar
#SOURCE_FILES
JAVAC_FLAGS=-sourcepath src -d build -classpath ${JAVA_CUP_PATH}
JAVA=java
JAVA_FLAGS=
PARSER=${JAVA} ${JAVA_FLAGS} java_cup.Main
PARSER_FLAGS=-locations -expect 100
LEXER=${JAVA} ${JAVA_FLAGS} JLex.Main

all :
	mkdir "build";
	${JAVAC} ${JAVC_FLAGS} src/latte/Compiler.java src/latte/*/*.java src/latte/*/*/*.java

cleanBuild : clean all

clean :
	rm -r build > /dev/null 2>/dev/null || true;
