// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

import frontend.SemanticError;

public class BStmt  extends Stmt {
  public final Block block_;
  public int line_num, col_num, offset;
  public BStmt(Block p1) { block_ = p1; }

  public <R,A> R accept(latte_lang.Absyn.Stmt.Visitor<R,A> v, A arg) throws SemanticError { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.BStmt) {
      latte_lang.Absyn.BStmt x = (latte_lang.Absyn.BStmt)o;
      return this.block_.equals(x.block_);
    }
    return false;
  }

  public int hashCode() {
    return this.block_.hashCode();
  }


}
