// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public class ClDefExt  extends TopDef {
  public final String ident_1, ident_2;
  public final ClBlock clblock_;
  public int line_num, col_num, offset;
  public ClDefExt(String p1, String p2, ClBlock p3) { ident_1 = p1; ident_2 = p2; clblock_ = p3; }

  public <R,A> R accept(latte_lang.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.ClDefExt) {
      latte_lang.Absyn.ClDefExt x = (latte_lang.Absyn.ClDefExt)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.clblock_.equals(x.clblock_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.clblock_.hashCode();
  }


}
