// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public class ClField  extends ClMember {
  public final Type type_;
  public final String ident_;
  public int line_num, col_num, offset;
  public ClField(Type p1, String p2) { type_ = p1; ident_ = p2; }

  public <R,A> R accept(latte_lang.Absyn.ClMember.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.ClField) {
      latte_lang.Absyn.ClField x = (latte_lang.Absyn.ClField)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.ident_.hashCode();
  }


}
