// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public class Decl  extends Stmt {
  public final Type type_;
  public final ListItem listitem_;
  public int line_num, col_num, offset;
  public Decl(Type p1, ListItem p2) { type_ = p1; listitem_ = p2; }

  public <R,A> R accept(latte_lang.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.Decl) {
      latte_lang.Absyn.Decl x = (latte_lang.Absyn.Decl)o;
      return this.type_.equals(x.type_) && this.listitem_.equals(x.listitem_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.listitem_.hashCode();
  }


}
