// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public class Div  extends MulOp {
  public int line_num, col_num, offset;
  public Div() { }

  public <R,A> R accept(latte_lang.Absyn.MulOp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.Div) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
