// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

import java.util.Objects;

public class ListClMember extends java.util.LinkedList<ClMember> {
    public ClMethod getMethod(String ident_) {
        for (int i = 0; i < this.size(); i++) {
            if (this.get(i).getClass() == ClMethod.class) {
                ClMethod method = (ClMethod) this.get(i);
                if (Objects.equals(method.ident_, ident_)) {
                    return method;
                }
            }
        }
        return null;
    }

    public ClField getField(String ident_) {
        for (int i = 0; i < this.size(); i++) {
            if (this.get(i).getClass() == ClField.class) {
                ClField field = (ClField) this.get(i);
                if (Objects.equals(field.ident_, ident_)) {
                    return field;
                }
            }
        }
        return null;
    }
}
