// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public abstract class MulOp implements java.io.Serializable {
  public abstract <R,A> R accept(MulOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte_lang.Absyn.Times p, A arg);
    public R visit(latte_lang.Absyn.Div p, A arg);
    public R visit(latte_lang.Absyn.Mod p, A arg);

  }

}
