// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public class NoInit  extends Item {
  public final String ident_;
  public int line_num, col_num, offset;
  public NoInit(String p1) { ident_ = p1; }

  public <R,A> R accept(latte_lang.Absyn.Item.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.NoInit) {
      latte_lang.Absyn.NoInit x = (latte_lang.Absyn.NoInit)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
