// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public class Prog  extends Program {
  public final ListTopDef listtopdef_;
  public int line_num, col_num, offset;
  public Prog(ListTopDef p1) { listtopdef_ = p1; }

  public <R,A> R accept(latte_lang.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte_lang.Absyn.Prog) {
      latte_lang.Absyn.Prog x = (latte_lang.Absyn.Prog)o;
      return this.listtopdef_.equals(x.listtopdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtopdef_.hashCode();
  }


}
