// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public abstract class RelOp implements java.io.Serializable {
  public abstract <R,A> R accept(RelOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte_lang.Absyn.LTH p, A arg);
    public R visit(latte_lang.Absyn.LE p, A arg);
    public R visit(latte_lang.Absyn.GTH p, A arg);
    public R visit(latte_lang.Absyn.GE p, A arg);
    public R visit(latte_lang.Absyn.EQU p, A arg);
    public R visit(latte_lang.Absyn.NE p, A arg);

  }

}
