// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte_lang.Absyn.Empty p, A arg);
    public R visit(latte_lang.Absyn.BStmt p, A arg);
    public R visit(latte_lang.Absyn.Decl p, A arg);
    public R visit(latte_lang.Absyn.Ass p, A arg);
    public R visit(latte_lang.Absyn.Incr p, A arg);
    public R visit(latte_lang.Absyn.Decr p, A arg);
    public R visit(latte_lang.Absyn.Ret p, A arg);
    public R visit(latte_lang.Absyn.VRet p, A arg);
    public R visit(latte_lang.Absyn.Cond p, A arg);
    public R visit(latte_lang.Absyn.CondElse p, A arg);
    public R visit(latte_lang.Absyn.While p, A arg);
    public R visit(latte_lang.Absyn.SExp p, A arg);

  }

}
