// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang.Absyn;

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte_lang.Absyn.Int p, A arg);
    public R visit(latte_lang.Absyn.Str p, A arg);
    public R visit(latte_lang.Absyn.Bool p, A arg);
    public R visit(latte_lang.Absyn.Void p, A arg);
    public R visit(latte_lang.Absyn.Class p, A arg);
    public R visit(latte_lang.Absyn.Array p, A arg);
    public R visit(latte_lang.Absyn.Fun p, A arg);
  }


}
