
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package latte.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_18 = 20;
  public static final int _SYMB_17 = 19;
  public static final int _SYMB_16 = 18;
  public static final int _SYMB_15 = 17;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_43 = 45;
  public static final int _SYMB_11 = 13;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_42 = 44;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_41 = 43;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_40 = 42;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int _IDENT_ = 48;
  public static final int _INTEGER_ = 47;
  public static final int _STRING_ = 46;
  public static final int _SYMB_39 = 41;
  public static final int _SYMB_38 = 40;
  public static final int _SYMB_37 = 39;
  public static final int _SYMB_36 = 38;
  public static final int _SYMB_35 = 37;
  public static final int _SYMB_34 = 36;
  public static final int _SYMB_33 = 35;
  public static final int _SYMB_32 = 34;
  public static final int _SYMB_31 = 33;
  public static final int _SYMB_30 = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int _SYMB_29 = 31;
  public static final int _SYMB_28 = 30;
  public static final int _SYMB_27 = 29;
  public static final int _SYMB_26 = 28;
  public static final int _SYMB_25 = 27;
  public static final int _SYMB_24 = 26;
  public static final int _SYMB_23 = 25;
  public static final int _SYMB_22 = 24;
  public static final int _SYMB_21 = 23;
  public static final int _SYMB_20 = 22;
  public static final int _SYMB_19 = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "_SYMB_0",
  "_SYMB_1",
  "_SYMB_2",
  "_SYMB_3",
  "_SYMB_4",
  "_SYMB_5",
  "_SYMB_6",
  "_SYMB_7",
  "_SYMB_8",
  "_SYMB_9",
  "_SYMB_10",
  "_SYMB_11",
  "_SYMB_12",
  "_SYMB_13",
  "_SYMB_14",
  "_SYMB_15",
  "_SYMB_16",
  "_SYMB_17",
  "_SYMB_18",
  "_SYMB_19",
  "_SYMB_20",
  "_SYMB_21",
  "_SYMB_22",
  "_SYMB_23",
  "_SYMB_24",
  "_SYMB_25",
  "_SYMB_26",
  "_SYMB_27",
  "_SYMB_28",
  "_SYMB_29",
  "_SYMB_30",
  "_SYMB_31",
  "_SYMB_32",
  "_SYMB_33",
  "_SYMB_34",
  "_SYMB_35",
  "_SYMB_36",
  "_SYMB_37",
  "_SYMB_38",
  "_SYMB_39",
  "_SYMB_40",
  "_SYMB_41",
  "_SYMB_42",
  "_SYMB_43",
  "_STRING_",
  "_INTEGER_",
  "_IDENT_"
  };
}

