import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class GoodVarqoxwarningsTest extends CompilerInputOutputErrTest {
//    @BeforeEach void setUp() {
//        super.setUp();
//        testUtils.setShouldGenerateExpectedOutput(true);
//    }
//    @AfterEach void tearDown() {
//        testUtils.setShouldGenerateExpectedOutput(false);
//        super.tearDown();
//    }
@Test void testDead_Code_After_While_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_while_true.lat", "lattests/good/varqoxwarnings/dead_code_after_while_true.output", "lattests/good/varqoxwarnings/dead_code_after_while_true.err", 0);}
@Test void testDead_Code_If_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_if_true.lat", "lattests/good/varqoxwarnings/dead_code_if_true.output", "lattests/good/varqoxwarnings/dead_code_if_true.err", 0);}
@Test void testBinop_Or_Left_Side_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/binop_or_left_side_true.lat", "lattests/good/varqoxwarnings/binop_or_left_side_true.output", "lattests/good/varqoxwarnings/binop_or_left_side_true.err", 0);}
@Test void testFor_Runs_At_Most_Once_Because_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/for_runs_at_most_once_because_return.lat", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_return.output", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_return.err", 0);}
@Test void testDead_Code_After_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_return.lat", "lattests/good/varqoxwarnings/dead_code_after_return.output", "lattests/good/varqoxwarnings/dead_code_after_return.err", 0);}
@Test void testArray_Negative_Subscript() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/array_negative_subscript.lat", "lattests/good/varqoxwarnings/array_negative_subscript.output", "lattests/good/varqoxwarnings/array_negative_subscript.err", 0);}
@Test void testWhile_Runs_At_Most_Once_Because_Void_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/while_runs_at_most_once_because_void_return.lat", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_void_return.output", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_void_return.err", 0);}
@Test void testArray_Subscript_Null_Array() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/array_subscript_null_array.lat", "lattests/good/varqoxwarnings/array_subscript_null_array.output", "lattests/good/varqoxwarnings/array_subscript_null_array.err", 0);}
@Test void testWhile_Runs_At_Most_Once_Because_While_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/while_runs_at_most_once_because_while_true.lat", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_while_true.output", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_while_true.err", 0);}
@Test void testDead_Code_After_Void_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_void_return.lat", "lattests/good/varqoxwarnings/dead_code_after_void_return.output", "lattests/good/varqoxwarnings/dead_code_after_void_return.err", 0);}
@Test void testDead_Code_In_While_After_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_while_after_return.lat", "lattests/good/varqoxwarnings/dead_code_in_while_after_return.output", "lattests/good/varqoxwarnings/dead_code_in_while_after_return.err", 0);}
@Test void testDead_Code_After_If_Else() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_if_else.lat", "lattests/good/varqoxwarnings/dead_code_after_if_else.output", "lattests/good/varqoxwarnings/dead_code_after_if_else.err", 0);}
@Test void testNew_Array_Negative_Size() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/new_array_negative_size.lat", "lattests/good/varqoxwarnings/new_array_negative_size.output", "lattests/good/varqoxwarnings/new_array_negative_size.err", 0);}
@Test void testDead_Code_In_For_After_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_for_after_return.lat", "lattests/good/varqoxwarnings/dead_code_in_for_after_return.output", "lattests/good/varqoxwarnings/dead_code_in_for_after_return.err", 0);}
@Test void testFor_Runs_At_Most_Once_Because_Error() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/for_runs_at_most_once_because_error.lat", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_error.output", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_error.err", 0);}
@Test void testDead_Code_In_While_After_While_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_while_after_while_true.lat", "lattests/good/varqoxwarnings/dead_code_in_while_after_while_true.output", "lattests/good/varqoxwarnings/dead_code_in_while_after_while_true.err", 0);}
@Test void testBinop_And_Right_Side_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/binop_and_right_side_true.lat", "lattests/good/varqoxwarnings/binop_and_right_side_true.output", "lattests/good/varqoxwarnings/binop_and_right_side_true.err", 0);}
@Test void testBinop_Or_Right_Side_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/binop_or_right_side_true.lat", "lattests/good/varqoxwarnings/binop_or_right_side_true.output", "lattests/good/varqoxwarnings/binop_or_right_side_true.err", 0);}
@Test void testMethod_Call_On_Null_Class() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/method_call_on_null_class.lat", "lattests/good/varqoxwarnings/method_call_on_null_class.output", "lattests/good/varqoxwarnings/method_call_on_null_class.err", 0);}
@Test void testDead_Code_If_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_if_false.lat", "lattests/good/varqoxwarnings/dead_code_if_false.output", "lattests/good/varqoxwarnings/dead_code_if_false.err", 0);}
@Test void testBinop_Or_Right_Side_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/binop_or_right_side_false.lat", "lattests/good/varqoxwarnings/binop_or_right_side_false.output", "lattests/good/varqoxwarnings/binop_or_right_side_false.err", 0);}
@Test void testDead_Code_After_If_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_if_true.lat", "lattests/good/varqoxwarnings/dead_code_after_if_true.output", "lattests/good/varqoxwarnings/dead_code_after_if_true.err", 0);}
@Test void testVar_Self_Comparison_Ne() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/var_self_comparison_ne.lat", "lattests/good/varqoxwarnings/var_self_comparison_ne.output", "lattests/good/varqoxwarnings/var_self_comparison_ne.err", 0);}
@Test void testBin_Op_Or_Left_Side_Always_False_Right_Side_Always_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/bin_op_or_left_side_always_false_right_side_always_true.lat", "lattests/good/varqoxwarnings/bin_op_or_left_side_always_false_right_side_always_true.output", "lattests/good/varqoxwarnings/bin_op_or_left_side_always_false_right_side_always_true.err", 0);}
@Test void testDead_Code_In_For_After_While_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_for_after_while_true.lat", "lattests/good/varqoxwarnings/dead_code_in_for_after_while_true.output", "lattests/good/varqoxwarnings/dead_code_in_for_after_while_true.err", 0);}
@Test void testBin_Op_And_Unknown_Right_Side_Always_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/bin_op_and_unknown_right_side_always_false.lat", "lattests/good/varqoxwarnings/bin_op_and_unknown_right_side_always_false.output", "lattests/good/varqoxwarnings/bin_op_and_unknown_right_side_always_false.err", 0);}
@Test void testBin_Op_And_Left_Side_Always_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/bin_op_and_left_side_always_false.lat", "lattests/good/varqoxwarnings/bin_op_and_left_side_always_false.output", "lattests/good/varqoxwarnings/bin_op_and_left_side_always_false.err", 0);}
@Test void testDead_Code_After_If_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_if_false.lat", "lattests/good/varqoxwarnings/dead_code_after_if_false.output", "lattests/good/varqoxwarnings/dead_code_after_if_false.err", 0);}
@Test void testDead_Code_In_While_After_Error() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_while_after_error.lat", "lattests/good/varqoxwarnings/dead_code_in_while_after_error.output", "lattests/good/varqoxwarnings/dead_code_in_while_after_error.err", 0);}
@Test void testDead_Code_After_If_Else_Nested() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_if_else_nested.lat", "lattests/good/varqoxwarnings/dead_code_after_if_else_nested.output", "lattests/good/varqoxwarnings/dead_code_after_if_else_nested.err", 0);}
@Test void testBin_Op_Or_Unknown_Right_Side_Always_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/bin_op_or_unknown_right_side_always_true.lat", "lattests/good/varqoxwarnings/bin_op_or_unknown_right_side_always_true.output", "lattests/good/varqoxwarnings/bin_op_or_unknown_right_side_always_true.err", 0);}
@Test void testBin_Op_Or_Left_Side_Always_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/bin_op_or_left_side_always_true.lat", "lattests/good/varqoxwarnings/bin_op_or_left_side_always_true.output", "lattests/good/varqoxwarnings/bin_op_or_left_side_always_true.err", 0);}
@Test void testDead_Code_After_Error() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_after_error.lat", "lattests/good/varqoxwarnings/dead_code_after_error.output", "lattests/good/varqoxwarnings/dead_code_after_error.err", 0);}
@Test void testNull_Class_Field() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/null_class_field.lat", "lattests/good/varqoxwarnings/null_class_field.output", "lattests/good/varqoxwarnings/null_class_field.err", 0);}
@Test void testNull_Array_Length() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/null_array_length.lat", "lattests/good/varqoxwarnings/null_array_length.output", "lattests/good/varqoxwarnings/null_array_length.err", 0);}
@Test void testDead_Code_In_For_After_Void_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_for_after_void_return.lat", "lattests/good/varqoxwarnings/dead_code_in_for_after_void_return.output", "lattests/good/varqoxwarnings/dead_code_in_for_after_void_return.err", 0);}
@Test void testDead_Code_In_For_After_Error() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_for_after_error.lat", "lattests/good/varqoxwarnings/dead_code_in_for_after_error.output", "lattests/good/varqoxwarnings/dead_code_in_for_after_error.err", 0);}
@Test void testBinop_And_Right_Side_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/binop_and_right_side_false.lat", "lattests/good/varqoxwarnings/binop_and_right_side_false.output", "lattests/good/varqoxwarnings/binop_and_right_side_false.err", 0);}
@Test void testVar_Self_Comparison_Eq() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/var_self_comparison_eq.lat", "lattests/good/varqoxwarnings/var_self_comparison_eq.output", "lattests/good/varqoxwarnings/var_self_comparison_eq.err", 0);}
@Test void testBin_Op_And_Left_Side_Always_True_Right_Side_Always_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/bin_op_and_left_side_always_true_right_side_always_false.lat", "lattests/good/varqoxwarnings/bin_op_and_left_side_always_true_right_side_always_false.output", "lattests/good/varqoxwarnings/bin_op_and_left_side_always_true_right_side_always_false.err", 0);}
@Test void testFor_Runs_At_Most_Once_Because_Void_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/for_runs_at_most_once_because_void_return.lat", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_void_return.output", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_void_return.err", 0);}
@Test void testFor_Runs_At_Most_Once_Because_While_True() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/for_runs_at_most_once_because_while_true.lat", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_while_true.output", "lattests/good/varqoxwarnings/for_runs_at_most_once_because_while_true.err", 0);}
@Test void testWhile_Runs_At_Most_Once_Because_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/while_runs_at_most_once_because_return.lat", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_return.output", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_return.err", 0);}
@Test void testBinop_And_Left_Side_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/binop_and_left_side_false.lat", "lattests/good/varqoxwarnings/binop_and_left_side_false.output", "lattests/good/varqoxwarnings/binop_and_left_side_false.err", 0);}
@Test void testDead_Code_In_While_After_Void_Return() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_in_while_after_void_return.lat", "lattests/good/varqoxwarnings/dead_code_in_while_after_void_return.output", "lattests/good/varqoxwarnings/dead_code_in_while_after_void_return.err", 0);}
@Test void testDead_Code_While_Cond_Always_False() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/dead_code_while_cond_always_false.lat", "lattests/good/varqoxwarnings/dead_code_while_cond_always_false.output", "lattests/good/varqoxwarnings/dead_code_while_cond_always_false.err", 0);}
@Test void testWhile_Runs_At_Most_Once_Because_Error() { testUtils.standardTestInputOutput("lattests/good/varqoxwarnings/while_runs_at_most_once_because_error.lat", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_error.output", "lattests/good/varqoxwarnings/while_runs_at_most_once_because_error.err", 0);}
}
