// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class Array  extends Type {
  public final Type type_;
  public int line_num, col_num, offset;
  public Array(Type p1) { type_ = p1; }

  public <R,A> R accept(latte.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.Array) {
      latte.Absyn.Array x = (latte.Absyn.Array)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }
  public boolean equalsT(java.lang.Object o) {
    if (this == o) return true;
    return o instanceof Array;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }

  @Override
  public String toString() {
    return type_ + "array";
  }
}
