// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class ClBlk  extends ClBlock {
  public final ListClMember listclmember_;
  public int line_num, col_num, offset;
  public ClBlk(ListClMember p1) { listclmember_ = p1; }

  public <R,A> R accept(latte.Absyn.ClBlock.Visitor<R,A> v, A arg) throws Exception { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClBlk) {
      latte.Absyn.ClBlk x = (latte.Absyn.ClBlk)o;
      return this.listclmember_.equals(x.listclmember_);
    }
    return false;
  }

  public int hashCode() {
    return this.listclmember_.hashCode();
  }


}
