// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class ClDef  extends TopDef {
  public final String ident_;
  public final ClBlock clblock_;
  public int line_num, col_num, offset;
  public ClDef(String p1, ClBlock p2) { ident_ = p1; clblock_ = p2; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) throws Exception { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClDef) {
      latte.Absyn.ClDef x = (latte.Absyn.ClDef)o;
      return this.ident_.equals(x.ident_) && this.clblock_.equals(x.clblock_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.clblock_.hashCode();
  }


}
