// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class ClFields  extends ClMember {
  public final Type type_;
  public final ListClFieldItem listclfielditem_;
  public int line_num, col_num, offset;
  public ClFields(Type p1, ListClFieldItem p2) { type_ = p1; listclfielditem_ = p2; }

  public <R,A> R accept(latte.Absyn.ClMember.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClFields) {
      latte.Absyn.ClFields x = (latte.Absyn.ClFields)o;
      return this.type_.equals(x.type_) && this.listclfielditem_.equals(x.listclfielditem_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.listclfielditem_.hashCode();
  }


}
