// File generated by the BNF Converter (bnfc 2.9.3).

package latte.Absyn;

public abstract class ClMember implements java.io.Serializable {
  public abstract <R,A> R accept(ClMember.Visitor<R,A> v, A arg) throws Exception;
  public interface Visitor <R,A> {
    R visit(latte.Absyn.ClField p, A arg);
    R visit(latte.Absyn.ClMethod p, A arg) throws Exception;

  }

}
