// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class ELitTrue  extends Expr {
  public int line_num, col_num, offset;
  public ELitTrue() { }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ELitTrue) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
