// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class EMethod  extends Expr {
  public final Expr expr_;
  public final String ident_;
  public final ListExpr listexpr_;
  public int line_num, col_num, offset;
  public EMethod(Expr p1, String p2, ListExpr p3) { expr_ = p1; ident_ = p2; listexpr_ = p3; }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.EMethod) {
      latte.Absyn.EMethod x = (latte.Absyn.EMethod)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_.hashCode())+this.ident_.hashCode())+this.listexpr_.hashCode();
  }


}
