// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class ENullArr  extends Expr {
  public final Type type_;
  public int line_num, col_num, offset;
  public ENullArr(Type p1) { type_ = p1; }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ENullArr) {
      latte.Absyn.ENullArr x = (latte.Absyn.ENullArr)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
