// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public class Int  extends Type {
  public int line_num, col_num, offset;
  public Int() { }

  public <R,A> R accept(latte.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
      return o instanceof Int;
  }

  @Override
  public String toString() {
    return "Int";
  }

  public int hashCode() {
    return 37;
  }


}
