// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

public abstract class Item implements java.io.Serializable {
  public abstract <R,A> R accept(Item.Visitor<R,A> v, A arg) throws Exception;
  public interface Visitor <R,A> {
    R visit(latte.Absyn.NoInit p, A arg) throws Exception;
    R visit(latte.Absyn.Init p, A arg) throws Exception;
  }

}
