// File generated by the BNF Converter (bnfc 2.9.4).

package latte.Absyn;

import java.util.Objects;

public class ListClMember extends java.util.LinkedList<ClMember> {
    public ClMethod getMethod(String ident_) {
        for (int i = 0; i < this.size(); i++) {
            if (this.get(i).getClass() == ClMethod.class) {
                ClMethod method = (ClMethod) this.get(i);
                if (Objects.equals(method.ident_, ident_)) {
                    return method;
                }
            }
        }
        return null;
    }

    public ClField getField(String ident_) {
        for (int i = 0; i < this.size(); i++) {
            if (this.get(i).getClass() == ClField.class) {
                ClField field = (ClField) this.get(i);
                if (Objects.equals(field.ident_, ident_)) {
                    return field;
                }
            }
            if (this.get(i).getClass() == ClFields.class) {
                ClFields field = (ClFields) this.get(i);
//                for (field in field.listclfielditem_)
                for (int j = 0; j < field.listclfielditem_.size(); j++) {
                    ClFieldItemNoInit fieldItem = (ClFieldItemNoInit) field.listclfielditem_.get(j);
                    if (Objects.equals(fieldItem.ident_, ident_)) {
                        ClField clField = new ClField(field.type_, fieldItem.ident_);
                        clField.col_num = field.col_num;
                        clField.line_num = field.line_num;
                        clField.offset = field.offset;
                        return clField;
                    }
                }
            }
        }
        return null;
    }
}
