// File generated by the BNF Converter (bnfc 2.9.3).

package latte.Absyn;

public abstract class Program implements java.io.Serializable {
  public abstract <R,A> R accept(Program.Visitor<R,A> v, A arg) throws Exception;
  public interface Visitor <R,A> {
    R visit(latte.Absyn.Prog p, A arg) throws Exception;

  }

}
