// File generated by the BNF Converter (bnfc 2.9.3).

package latte.Absyn;

import latte.errors.SemanticError;

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg) throws SemanticError;
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.Empty p, A arg);
    public R visit(latte.Absyn.BStmt p, A arg) throws SemanticError;
    public R visit(latte.Absyn.Decl p, A arg) throws SemanticError;
    public R visit(latte.Absyn.Ass p, A arg) throws SemanticError;
    public R visit(latte.Absyn.AssArray p, A arg) throws SemanticError;
    public R visit(latte.Absyn.AssField p, A arg) throws SemanticError;
    public R visit(latte.Absyn.Incr p, A arg) throws SemanticError;
    public R visit(latte.Absyn.Decr p, A arg) throws SemanticError;
    public R visit(latte.Absyn.Ret p, A arg) throws SemanticError;
    public R visit(latte.Absyn.VRet p, A arg) throws SemanticError;
    public R visit(latte.Absyn.Cond p, A arg) throws SemanticError;
    public R visit(latte.Absyn.CondElse p, A arg) throws SemanticError;
    public R visit(latte.Absyn.While p, A arg) throws SemanticError;
    public R visit(latte.Absyn.For p, A arg) throws SemanticError;
    public R visit(latte.Absyn.SExp p, A arg) throws SemanticError;

  }

}
