// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang;

/** All Visitor */

public interface AllVisitor<R,A> extends
  latte_lang.Absyn.Program.Visitor<R,A>,
  latte_lang.Absyn.TopDef.Visitor<R,A>,
  latte_lang.Absyn.Arg.Visitor<R,A>,
  latte_lang.Absyn.ClBlock.Visitor<R,A>,
  latte_lang.Absyn.ClMember.Visitor<R,A>,
  latte_lang.Absyn.Block.Visitor<R,A>,
  latte_lang.Absyn.Stmt.Visitor<R,A>,
  latte_lang.Absyn.Item.Visitor<R,A>,
  latte_lang.Absyn.Type.Visitor<R,A>,
  latte_lang.Absyn.Expr.Visitor<R,A>,
  latte_lang.Absyn.AddOp.Visitor<R,A>,
  latte_lang.Absyn.MulOp.Visitor<R,A>,
  latte_lang.Absyn.RelOp.Visitor<R,A>
{}
