// File generated by the BNF Converter (bnfc 2.9.3).

package latte_lang;

/** Fold Visitor */
public abstract class FoldVisitor<R,A> implements AllVisitor<R,A> {
    public abstract R leaf(A arg);
    public abstract R combine(R x, R y, A arg);

/* Program */
    public R visit(latte_lang.Absyn.Prog p, A arg) {
      R r = leaf(arg);
      for (latte_lang.Absyn.TopDef x : p.listtopdef_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* TopDef */
    public R visit(latte_lang.Absyn.FnDef p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      for (latte_lang.Absyn.Arg x : p.listarg_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.block_.accept(this, arg), r, arg);
      return r;
    }

/* Arg */
    public R visit(latte_lang.Absyn.Ar p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* Block */
    public R visit(latte_lang.Absyn.Blk p, A arg) {
      R r = leaf(arg);
      for (latte_lang.Absyn.Stmt x : p.liststmt_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Stmt */
    public R visit(latte_lang.Absyn.Empty p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.BStmt p, A arg) {
      R r = leaf(arg);
      r = combine(p.block_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Decl p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      for (latte_lang.Absyn.Item x : p.listitem_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(latte_lang.Absyn.Ass p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Incr p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Decr p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Ret p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.VRet p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Cond p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.stmt_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.CondElse p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.stmt_1.accept(this, arg), r, arg);
      r = combine(p.stmt_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.While p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.stmt_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.SExp p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Item */
    public R visit(latte_lang.Absyn.NoInit p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Init p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Type */
    public R visit(latte_lang.Absyn.Int p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Str p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Bool p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Void p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Fun p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      for (latte_lang.Absyn.Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Expr */
    public R visit(latte_lang.Absyn.EVar p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.ELitInt p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.ELitTrue p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.ELitFalse p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.EApp p, A arg) {
      R r = leaf(arg);
      for (latte_lang.Absyn.Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(latte_lang.Absyn.EString p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Neg p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Not p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.EMul p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.mulop_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.EAdd p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.addop_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.ERel p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.relop_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.EAnd p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(latte_lang.Absyn.EOr p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }

/* AddOp */
    public R visit(latte_lang.Absyn.Plus p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Minus p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* MulOp */
    public R visit(latte_lang.Absyn.Times p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Div p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.Mod p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* RelOp */
    public R visit(latte_lang.Absyn.LTH p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.LE p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.GTH p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.GE p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.EQU p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(latte_lang.Absyn.NE p, A arg) {
      R r = leaf(arg);
      return r;
    }


}
